version: "3.2"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:50000
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel
  postgres:
    image: postgres:12
    container_name: postgres
    restart: unless-stopped
    volumes:
     - ./postgres/pg_data:/var/lib/postgresql/data
    env_file: .env
    ports:
     - 5432:50123
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:50000
    networks:
      - laravel
networks:
  laravel:
    




    
      